version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - '5436:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: always
    healthcheck:
      test: "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: application
    ports:
      - '${SRV_PORT}:${SRV_PORT}'
    environment:
      SRV_PORT: ${SRV_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data: